ops:
  - changed-files:
      - any-glob-to-any-file: ['scripts/**', '.github/**', 'Makefile']

python:
  - changed-files:
      - any-glob-to-any-file: ['src/**', 'tests/**', '*.py']

docs:
  - changed-files:
      - any-glob-to-any-file: ['docs/**', '**/*.md']
