name: Auto Cleanup Branch After PR Merge

on:
  pull_request_target:
    types: [closed]

permissions:
  contents: write

jobs:
  cleanup:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.head.ref != github.event.repository.default_branch
    runs-on: ubuntu-latest
    steps:
      - name: Delete head branch
        uses: actions/github-script@v7
        with:
          script: |
            const headRef = context.payload.pull_request.head.ref;
            core.info(`Deleting branch ${headRef}`);
            await github.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `heads/${headRef}`,
            });
