name: CI - Lint & Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install test tools (ruff, pytest); project deps if requirements.txt is present
          python -m pip install ruff pytest || true
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt || true; fi

      - name: Run ruff (lint)
        run: |
          python -m ruff check .

      - name: Run pytest
        run: |
          pytest -q

  # optional typecheck job can be added later

  typecheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache mypy cache
        uses: actions/cache@v4
        with:
          path: .mypy_cache
          key: mypy-${{ runner.os }}-${{ hashFiles('**/*.py') }}

      - name: Install mypy
        run: |
          python -m pip install --upgrade pip
          python -m pip install mypy || true
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt || true; fi

      - name: Run mypy (light)
        run: |
          # Use ignore-missing-imports to avoid blocking on optional deps
          mypy --ignore-missing-imports . || true
