name: CI - Lint & Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install ruff
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff || true

      - name: Run ruff (lint)
        run: |
          python -m ruff check .

  test:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest || true
          # Prefer the minimal requirements in CI to keep installs fast and reliable
          if [ -f requirements-min.txt ]; then
            python -m pip install -r requirements-min.txt || true
          elif [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt || true
          fi

      - name: Run pytest
        run: |
          python -m pytest -q

  # optional typecheck job can be added later

  typecheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache mypy cache
        uses: actions/cache@v4
        with:
          path: .mypy_cache
          key: mypy-${{ runner.os }}-${{ hashFiles('src/**/*.py') }}

      - name: Install mypy
        run: |
          python -m pip install --upgrade pip
          python -m pip install mypy || true
          # Prefer the minimal requirements in CI to keep installs fast and reliable
          if [ -f requirements-min.txt ]; then
            python -m pip install -r requirements-min.txt || true
          elif [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt || true
          fi

      - name: Run mypy (light)
        run: |
          # Only type-check the package source to avoid duplicate modules in docs/
          # Exclude docs and conversations-pocket which contain archived copies
          # and may shadow modules in src.
          mypy --ignore-missing-imports --exclude 'docs|conversations-pocket' src || true
