name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    strategy:
      matrix:
        mode: [smoke, full]
    env:
      PERF_CANARY: '0'
      PERF_MIN_THR: '5'
      PERF_ITEMS: '50'
      APPLY_UPDATES: '0'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Install Node dependencies
        run: npm install
      - name: Smoke chat and assertions
        if: matrix.mode == 'smoke'
        run: |
          make chat-smoke
          test -f artifacts/ci_smoke/chat.log
          grep -q 'x\*\*2 - 1' artifacts/ci_smoke/chat.log
          grep -q '"math_available":' artifacts/ci_smoke/chat.log
          grep -q '"sympy_version":' artifacts/ci_smoke/chat.log
      - name: Apply manifesto updates optional
        if: matrix.mode == 'smoke' && env.APPLY_UPDATES == '1'
        run: |
          python scripts/apply_manifesto_updates.py
          python -m scripts.validate_operators
          pytest -q --maxfail=1 --disable-warnings
          make sitrep
      - name: Run Python tests
        if: matrix.mode == 'full'
        run: pytest -q
      - name: Run Node tests
        if: matrix.mode == 'full'
        run: npm test
      - name: Operator validator gate
        run: |
          python scripts/validate_operators.py
          python - <<'PY'
          import json,sys
          d=json.load(open('artifacts/ci_smoke/operator_mapping.json'))
          assert d.get('refs_ok') is True and not d.get('errors'), d
          PY
      - name: Contradiction quick check
        if: matrix.mode == 'full'
        run: |
          python - <<'PY'
          from tools.logic.detector import detect
          assert detect(["P(a)","not P(a)"])['x_g'] > 0.0
          assert detect(["P(a)","Q(a)"])['x_g'] == 0.0
          PY
      - name: Archive ontology mapping
        uses: actions/upload-artifact@v4
        with:
          name: operator-mapping-${{ matrix.mode }}
          path: artifacts/ci_smoke/operator_mapping.*