name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    env:
      PERF_CANARY: '0'
      PERF_MIN_THR: '5'
      PERF_ITEMS: '50'
      APPLY_UPDATES: '0'   # set to '1' to auto-apply manifesto/updates in smoke job
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # ensure pytest is available even if console scripts are missing
          python -m pip install pytest || true
          # prefer minimal requirements to keep CI fast; fall back to full requirements
          if [ -f requirements-min.txt ]; then
            python -m pip install -r requirements-min.txt || true
          elif [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt || true
          fi
      - name: Install Node dependencies
        run: npm install
      - name: Run Python tests
        run: python -m pytest -q
      - name: Run Node tests (skip if none)
        run: |
          # Run jest but allow zero tests without failing the pipeline
          npm test -- --passWithNoTests
      - name: Operator validator gate
        run: |
          python scripts/validate_operators.py
          python - <<'PY'
          import json,sys
          d=json.load(open('artifacts/ci_smoke/operator_mapping.json'))
          assert d.get('refs_ok') is True and not d.get('errors'), d
          PY
      - name: Contradiction quick check
        run: |
          python - <<'PY'
          from tools.logic.detector import detect
          assert detect(["P(a)","not P(a)"])['x_g'] > 0.0
          assert detect(["P(a)","Q(a)"])['x_g'] == 0.0
          PY
      - name: Archive ontology mapping
        uses: actions/upload-artifact@v4
        with:
          name: operator-mapping
          path: artifacts/ci_smoke/operator_mapping.*
      - name: Apply manifesto updates (optional)
        if: env.APPLY_UPDATES == '1'
        run: |
          python scripts/apply_manifesto_updates.py
          python -m scripts.validate_operators
          python -m pytest -q --maxfail=1 --disable-warnings
