name: CI

on:
  push:
    branches: [ main, refactor/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Set deterministic environment
      run: |
        echo "PYTHONHASHSEED=0" >> $GITHUB_ENV
        echo "OMP_NUM_THREADS=1" >> $GITHUB_ENV
        echo "OPENBLAS_NUM_THREADS=1" >> $GITHUB_ENV
        echo "MKL_NUM_THREADS=1" >> $GITHUB_ENV
        echo "NUMEXPR_NUM_THREADS=1" >> $GITHUB_ENV
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest ruff
        pip install -e .
    
    - name: Lint with ruff
      run: |
        ruff check src/ tests/ --output-format=github
      continue-on-error: true
    
    - name: Run fast tests
      run: |
        pytest tests/ -v --tb=short -x -m "not slow" --maxfail=5
    
    - name: Validate determinism compliance
      run: |
        python -c "from src.determinism import assert_deterministic_environment; assert_deterministic_environment()"
        python -c "from src.determinism import validate_rng_policy; validate_rng_policy()"
    
    - name: Validate metrics endpoint
      run: |
        python metrics_server.py --test
    
    - name: Test CLI functionality
      run: |
        python koriel-run status
        python koriel-run run --dry-run
        python koriel-run experiment --name test --dry-run || true

  nightly:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    
    - name: Set deterministic environment
      run: |
        echo "PYTHONHASHSEED=0" >> $GITHUB_ENV
        echo "OMP_NUM_THREADS=1" >> $GITHUB_ENV
        echo "OPENBLAS_NUM_THREADS=1" >> $GITHUB_ENV
        echo "MKL_NUM_THREADS=1" >> $GITHUB_ENV
        echo "NUMEXPR_NUM_THREADS=1" >> $GITHUB_ENV
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -e .
    
    - name: Run all tests including slow ones
      run: |
        pytest tests/ -v --tb=short
      timeout-minutes: 30
    
    - name: Run experiment safety tests
      run: |
        python koriel-run experiment --name brutal_consciousness_validation --allow-experiments --dry-run
        python koriel-run experiment --name extreme_qrft_stress_test --allow-experiments --dry-run