name: CI

on:
  push:
    branches: [ main, refactor/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -e .
    
    - name: Lint with ruff (if available)
      run: |
        pip install ruff || echo "Ruff not available, skipping"
        ruff check src/ tests/ || echo "Linting failed or ruff not available"
      continue-on-error: true
    
    - name: Run fast tests
      run: |
        pytest tests/ -v --tb=short -x -m "not slow"
      continue-on-error: true
    
    - name: Test package import
      run: |
        python -c "import sys; sys.path.insert(0, 'src'); import train; print('Basic import successful')"