name: Lint

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pre-commit and hooks
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit install-hooks
      - name: Run pre-commit
        run: pre-commit run --all-files
