name: PR Intake Triage

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Apply labels by heuristics
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const title = pr.title || '';
            const head = pr.head.ref || '';
            const author = pr.user.login || '';
            const labels = new Set();
            // Mark likely agent PRs
            if (head.startsWith('copilot/') || head.startsWith('codex/') || author.toLowerCase().includes('bot')) {
              labels.add('agent');
            }
            if (title.toLowerCase().includes('wip') || pr.draft) labels.add('wip');
            // Perm probe PRs
            if (title.toLowerCase().includes('perm-probe') || head.startsWith('probe/')) labels.add('perm-probe');
            // Automerge hint for safe probes
            if (labels.has('perm-probe')) labels.add('automerge');
            if (labels.size > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: Array.from(labels),
              });
            }
      - name: Comment with intake checklist and commands
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const body = `### Intake
            PR #${pr.number} from \`${pr.head.ref}\` by @${pr.user.login}

            Checklist:
            - [ ] CI green (tests + lint)
            - [ ] No binary artifacts committed
            - [ ] Labels set (agent/docs/python/ops)
            - [ ] Ready for auto-merge? Add label: automerge

            Commands (comment on this PR):
            - /sitrep — generate branch/PR sitrep artifact
            - /automerge — request auto-merge (on green)
            - /adopt — create an adoption branch to integrate with main
            - /label name — add label (e.g., /label docs)
            `;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body,
            });
