name: Release on Tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate release notes
        id: notes
        uses: actions/github-script@v7
        with:
          script: |
            const tag = context.ref.replace('refs/tags/', '');
            const body = `Automated release for ${tag}.\n\nSee CI artifacts and sitrep for details.`;
            core.setOutput('tag', tag);
            core.setOutput('body', body);
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.notes.outputs.tag }}
          name: ${{ steps.notes.outputs.tag }}
          body: ${{ steps.notes.outputs.body }}
          draft: false
          prerelease: false
