name: Examples smoke

on:
  push:
	branches: [ main, ops/**, ci/**, feat/**, fix/** ]
  pull_request:
	branches: [ main ]

jobs:
  examples-smoke:
	runs-on: ubuntu-latest
	steps:
	  - uses: actions/checkout@v4

	  - name: Set up Python
		uses: actions/setup-python@v5
		with:
		  python-version: '3.12'

	  - name: Install dependencies
		run: |
		  python -m pip install --upgrade pip
		  pip install -e .
		  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
		  # Required by koriel quantum field modules
		  pip install matplotlib scipy

	  - name: Run example smoke
		env:
		  PYTHONPATH: src
		run: |
		  python examples/koriel_demo.py

